alter schema dbo TRANSFER [arsshina].[Diesel_Train_Infos]
alter schema dbo TRANSFER [arsshina].[Diesel_Trinzs]
alter schema dbo TRANSFER [arsshina].[DieselLocomoives]
alter schema dbo TRANSFER [arsshina].[DieselLocomotiveInfos]
alter schema dbo TRANSFER [arsshina].[DieselTrainzLists]
alter schema dbo TRANSFER [arsshina].[DizelTrainzLists]
alter schema dbo TRANSFER [arsshina].[Electic_Locomotives]
alter schema dbo TRANSFER [arsshina].[ElectrickTrainsList]
alter schema dbo TRANSFER [arsshina].[ElectrickTrainzInformation]
alter schema dbo TRANSFER [arsshina].[IpAdresses]
alter schema dbo TRANSFER [arsshina].[Electrics]
alter schema dbo TRANSFER [arsshina].[ListRollingStones]
alter schema dbo TRANSFER [arsshina].[locomotiveBaseInfos]
alter schema dbo TRANSFER [arsshina].[MainImages]
alter schema dbo TRANSFER [arsshina].[LocomotivesTypes]
alter schema dbo TRANSFER [arsshina].[MetroLines]
alter schema dbo TRANSFER [arsshina].[Metros]
alter schema dbo TRANSFER [arsshina].[NewsComments]
alter schema dbo TRANSFER [arsshina].[NewsInfos]
alter schema dbo TRANSFER [arsshina].[Oblasts]
alter schema dbo TRANSFER [arsshina].[PassangerCarriegesInfos]
alter schema dbo TRANSFER [arsshina].[PassangerCarrieres]
alter schema dbo TRANSFER [arsshina].[plants]
alter schema dbo TRANSFER [arsshina].[RailwayUsersPhotos]
alter schema dbo TRANSFER [arsshina].[Roles]
alter schema dbo TRANSFER [arsshina].[stationInfos]
alter schema dbo TRANSFER [arsshina].[StationsShadules]
alter schema dbo TRANSFER [arsshina].[Stations]
alter schema dbo TRANSFER [arsshina].[Statuses]
alter schema dbo TRANSFER [arsshina].[SuburbanTrainsInfos]
alter schema dbo TRANSFER [arsshina].[Trains]
alter schema dbo TRANSFER [arsshina].[TrainsShadule]
alter schema dbo TRANSFER [arsshina].[TrainzStations]
alter schema dbo TRANSFER [arsshina].[TrainzTypes]
alter schema dbo TRANSFER [arsshina].[TypeOfPassTrains]
alter schema dbo TRANSFER [arsshina].[UkrainsRailways]
alter schema dbo TRANSFER [arsshina].[User]
alter schema dbo TRANSFER [arsshina].[UserLocomotivePhotos]
alter schema dbo TRANSFER [arsshina].[UserTrainzPhotos]
alter schema dbo TRANSFER [dbo].[__EFMigrationsHistory]
alter schema dbo TRANSFER [dbo].[CargoCarrieges]
alter schema dbo TRANSFER [dbo].[CargoCarriegesInfos]
alter schema dbo TRANSFER [dbo].[Depots]
alter schema dbo TRANSFER [dbo].[Cities]
alter schema dbo TRANSFER [dbo].[Clients]
alter schema dbo TRANSFER [arsshina].[MetroStations]
alter schema dbo TRANSFER [arsshina].[Locomotive_Series]
alter schema dbo TRANSFER [arsshina].[Electrick_Lockomotive_Infos]





